[tool.poetry]
name = "agentic-ragß"
version = "0.1.0"
description = ""
authors = ["Abhi Pad <abhishekhp@gmail.com>"]
readme = "README.md"
package-mode = false  # <--- ADD THIS LINE

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
langchain = "*"
langgraph = "*"
langchain-openai = "*"
langchainhub = "*"
black = "*"
isort = "*"
python-dotenv = "*"
langchain-tavily = "*"
beautifulsoup4 = "^4.14.3"
langchain-community = "^0.4.2"
tavily-python = "^0.7.24"
chromadb = "^1.5.9"
pytest = "^9.0.3"
langchain-pinecone = "^0.2.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
